### PR TITLE
Adding rng functions to generator. Also fixing types for seeds to be …

### PR DESCRIPTION
**Pull request by elenaran**
Was planning on using some of these functions in an example. Let me know if this isn't the best way to include them

### CODE REVIEW

**Comment by ScriptLineStudios** [comment]
Thanks for the PR! I'm definitely on board with having RNG functions be part of the API.

I agree the chunkGenerateRnd should be part of the finder object, but I wonder if the more general RNG functions should be moved out into their object, something along the lines of:

```python
rng = pybiomes.Rng()
rng.set_seed(12345)
long = rng.next_long()
```

This would allow for the seed to be stored internally, instead of having to be passed as an argument every time.

What do you think?

**Comment by ScriptLineStudios** [comment]
Also, do you think you could split this into 2 PRs? The other changes look good and ready to merge ;)

**Comment by elenaran** [comment]
Yeah I was wondering if I should make a separate Rng object. OK I rebased and just committed the Finders chunk random gen function

**Comment by ScriptLineStudios** [comment]
Thanks, Looks good to me! :tada:

**Pull request merged**
